package com.entity;

// Generated 2015-5-7 16:11:59 by Hibernate Tools 4.0.0

/**
 * ConnectType generated by hbm2java
 */
public class ConnectType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6724643239273673806L;
	private Integer id;
	private String typeName;

	public ConnectType() {
	}

	public ConnectType(String typeName) {
		this.typeName = typeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
