package com.entity;

// Generated 2015-5-7 16:11:59 by Hibernate Tools 4.0.0

/**
 * Connect generated by hbm2java
 */
public class Connect implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8066620035411909146L;
	private Integer connectId;
	private String connectName;
	private int connectTypeId;
	private String connectIp;
	private int connectPort;
	private String connectUserName;
	private String connectPassword;

	public Connect() {
	}

	public Connect(String connectName, int connectTypeId, String connectIp, int connectPort, String connectUserName, String connectPassword) {
		this.connectName = connectName;
		this.connectTypeId = connectTypeId;
		this.connectIp = connectIp;
		this.connectPort = connectPort;
		this.connectUserName = connectUserName;
		this.connectPassword = connectPassword;
	}

	public Integer getConnectId() {
		return this.connectId;
	}

	public void setConnectId(Integer connectId) {
		this.connectId = connectId;
	}

	public String getConnectName() {
		return this.connectName;
	}

	public void setConnectName(String connectName) {
		this.connectName = connectName;
	}

	public int getConnectTypeId() {
		return this.connectTypeId;
	}

	public void setConnectTypeId(int connectTypeId) {
		this.connectTypeId = connectTypeId;
	}

	public String getConnectIp() {
		return this.connectIp;
	}

	public void setConnectIp(String connectIp) {
		this.connectIp = connectIp;
	}

	public int getConnectPort() {
		return this.connectPort;
	}

	public void setConnectPort(int connectPort) {
		this.connectPort = connectPort;
	}

	public String getConnectUserName() {
		return this.connectUserName;
	}

	public void setConnectUserName(String connectUserName) {
		this.connectUserName = connectUserName;
	}

	public String getConnectPassword() {
		return this.connectPassword;
	}

	public void setConnectPassword(String connectPassword) {
		this.connectPassword = connectPassword;
	}

}
