package com.entity;

// Generated 2015-5-7 16:11:59 by Hibernate Tools 4.0.0

/**
 * Departments generated by hbm2java
 */
public class Departments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3850601841410821019L;
	private Integer id;
	private String depName;

	public Departments() {
	}

	public Departments(String depName) {
		this.depName = depName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

}
