package com.entity;

// Generated 2015-5-19 17:18:39 by Hibernate Tools 4.0.0

/**
 * SourceTable generated by hbm2java
 */
public class SourceTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7868601637336386982L;
	private Integer id;
	private int taskId;
	private String sourceTableName;

	public SourceTable() {
	}

	public SourceTable(int taskId, String sourceTableName) {
		this.taskId = taskId;
		this.sourceTableName = sourceTableName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public String getSourceTableName() {
		return this.sourceTableName;
	}

	public void setSourceTableName(String sourceTableName) {
		this.sourceTableName = sourceTableName;
	}

}
