package com.entity;

// Generated 2015-5-20 15:45:29 by Hibernate Tools 4.0.0

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6991123200577227486L;
	private Integer id;
	private boolean importType;
	private boolean importIsDb;
	private int sourceConnectId;
	private String sourceDatebaseName;
	private int receivedConnectId;
	private String receivedDatebaseName;
	private String remarks;

	public Task() {
	}

	public Task(boolean importType, boolean importIsDb, int sourceConnectId, String sourceDatebaseName, int receivedConnectId, String receivedDatebaseName, String remarks) {
		this.importType = importType;
		this.importIsDb = importIsDb;
		this.sourceConnectId = sourceConnectId;
		this.sourceDatebaseName = sourceDatebaseName;
		this.receivedConnectId = receivedConnectId;
		this.receivedDatebaseName = receivedDatebaseName;
		this.remarks = remarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public boolean isImportType() {
		return this.importType;
	}

	public void setImportType(boolean importType) {
		this.importType = importType;
	}

	public boolean isImportIsDb() {
		return this.importIsDb;
	}

	public void setImportIsDb(boolean importIsDb) {
		this.importIsDb = importIsDb;
	}

	public int getSourceConnectId() {
		return this.sourceConnectId;
	}

	public void setSourceConnectId(int sourceConnectId) {
		this.sourceConnectId = sourceConnectId;
	}

	public String getSourceDatebaseName() {
		return this.sourceDatebaseName;
	}

	public void setSourceDatebaseName(String sourceDatebaseName) {
		this.sourceDatebaseName = sourceDatebaseName;
	}

	public int getReceivedConnectId() {
		return this.receivedConnectId;
	}

	public void setReceivedConnectId(int receivedConnectId) {
		this.receivedConnectId = receivedConnectId;
	}

	public String getReceivedDatebaseName() {
		return this.receivedDatebaseName;
	}

	public void setReceivedDatebaseName(String receivedDatebaseName) {
		this.receivedDatebaseName = receivedDatebaseName;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
